@extends('layouts.login-template', [
    'title' => 'Staff',
    'bgImage' => '/images/staff-login-bg.jpg',
    'btnColorToken' => '--color-secondary',
    'btnColorOnToken' => '--color-on-secondary',
    'btnHoverDark' => '#88dbb3',
    'btnHoverLight' => '#2db876',
    'spinnerColorToken' => '--color-on-secondary',
    'idLabel' => 'Staff ID',
    'idPlaceholder' => 'e.g. 6767',
    'idRegex' => '^\d+$',
    'formatHint' => 'Numeric staff ID only',
    'loginType' => 'staff',
    'roleSwitchHtml' => 'Student? <a href="' . route('login.student') . '">Student Login</a>',
    'rememberHint' => 'Keep me logged in for 30 minutes',
    'showLockout' => true,
])
