@extends('layouts.login-template', [
    'title' => 'Student',
    'bgImage' => '/images/student-login-bg.jpg',
    'btnColorToken' => '--color-primary',
    'btnColorOnToken' => '--color-on-primary',
    'btnHoverDark' => '#154d94',
    'btnHoverLight' => '#154d94',
    'spinnerColorToken' => '--color-on-primary',
    'idLabel' => 'Student ID',
    'idPlaceholder' => 'e.g. 25RSD0001',
    'idRegex' => '^\d{2}[A-Za-z]{3}\d{4}$',
    'formatHint' => 'Format: 2 digits + 3 letters + 4 digits',
    'loginType' => 'student',
    'roleSwitchHtml' => 'Staff? <a href="' . route('login.staff') . '">Staff Login</a>',
    'rememberHint' => 'Keep me logged in for 30 days',
])
